### ISSUE TITLE
[NFR]: 4.1.0 Checklist

### ISSUE THREAD

**Issue by niden** [phalcon/cphalcon#15197]
Phalcon 4.1.0 will be released on 10-31-2020. This is our todo list for the release.
Pull regarding the release can reference this issue

* [x] Check pending pulls that need to be merged with 4.1.0
* [x] Update ext + build dir with Zephir 0.12.17 and verify generation
* [x] Update release notes and date package.xml (Pecl)
* [x] Tag release in Github / prepare release notes
* [x] Upload Pecl package to Pecl
* [x] PackageCloud packages
* [x] Create blog post
* [ ] Post to social.zoho.com
* [x] Post to Gab.com
* [x] Post to parler.com
* [x] Post to mewe.com
* [x] Post to telegram
* [x] Ping freebsd / openbsd maintainer
* [x] Post to LinkedIn
* [x] Update & release stubs
* [x] Update PhpStorm Stubs plugin
* [ ] Update wikipedia
* [x] Update Homebrew package
* [x] Update Docs

**Comment by steveobbayi** [comment]
How about updating the official docs with the new features

**Comment by ruudboon** [comment]
@steveobbayi good point. Added it to the todo.

**Comment by Jeckerson** [comment]
Related - https://github.com/phalcon/docs/issues/2810
